[package]
name = "lc3vm"
version = "0.1.0"
authors = ["nico"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.18.0"
termios = "0.3.2"